#!/bin/bash
echo "HELLO GUYS IAM LEARNING AWS AND DEVOPS FROM MICRODEGREE"
echo "HELLO GUYS IAM LEARNING AWS AND DEVOPS FROM MICRODEGREE"
echo "HELLO GUYS IAM LEARNING AWS AND DEVOPS FROM MICRODEGREE"
echo "HELLO GUYS IAM LEARNING AWS AND DEVOPS FROM MICRODEGREE"
echo "HELLO GUYS IAM LEARNING AWS AND DEVOPS FROM MICRODEGREE"
